name: CI/CD for MLflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          pytest

      - name: Log model to MLflow
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          # MLFLOW_TRACKING_TOKEN: ${{ secrets.MLFLOW_TRACKING_TOKEN }}
        run: |
          python scripts/log_model.py
          echo "MLFLOW_RUN_ID=$(cat run_id.txt)" >> $GITHUB_ENV

      - name: Check MLflow connection
        run: |
          python -c "import mlflow; print(mlflow.get_tracking_uri()); print(mlflow.list_experiments())"

      - name: Test deployed model
        env:
          MLFOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          python scripts/test_model.py
